name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore src/Consolpunke
    - name: Build
      run: dotnet build src/Consolpunke --configuration Release --no-restore /p:VersionSuffix=build.$GITHUB_RUN_ID
    - name: Unit Test
      run: dotnet test src/Consolpunke.Tests --configuration Release
    - name: Smoke Test
      run: |
        dotnet tool install -g Consolpunke -add-source bin/Release
        consolpunke --version