name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore src/Consolpunke.Tests
    - name: Build
      run: dotnet build src/Consolpunke.Tests --configuration Release --no-restore
    - name: Test
      run: dotnet test src/Consolpunke.Tests --configuration Release --no-build
    - name: Package
      run: dotnet pack src/Consolpunke --no-restore --include-symbols --include-source --no-build
